"""init

Revision ID: 9d3bc00941b1
Revises: 
Create Date: 2025-04-24 23:31:46.542106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3bc00941b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('eval_date', sa.Date(), nullable=False),
    sa.Column('training_status', sa.String(length=10), nullable=True),
    sa.Column('fitness', sa.String(length=10), nullable=True),
    sa.Column('sleep', sa.String(length=10), nullable=True),
    sa.Column('appetite', sa.String(length=10), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('jump_type', sa.String(length=50), nullable=True),
    sa.Column('jump_count', sa.Integer(), nullable=True),
    sa.Column('run_distance', sa.Float(), nullable=True),
    sa.Column('run_time', sa.String(length=20), nullable=True),
    sa.Column('weight_part', sa.String(length=50), nullable=True),
    sa.Column('weight_sets', sa.Integer(), nullable=True),
    sa.Column('agility_type', sa.String(length=50), nullable=True),
    sa.Column('agility_note', sa.Text(), nullable=True),
    sa.Column('special_focus', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training')
    op.drop_table('evaluation')
    op.drop_table('announcement')
    op.drop_table('user')
    # ### end Alembic commands ###
